In [14]:
import pandas
import matplotlib
import torch
import numpy

Bài 1: Tạo 1 Tensor

In [5]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Bài 2: Tạo các Tensor thường dùng

In [6]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.2989, 0.6053, 0.5821, 0.1406],
        [0.0149, 0.1360, 0.8900, 0.5525],
        [0.2777, 0.8496, 0.4556, 0.3600]])
tensor([[ 0.0323,  0.5243,  0.6704,  0.2466],
        [-0.3525,  1.0164, -0.3699,  0.5170],
        [-0.2397, -1.2816,  1.0965,  0.0941]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


Bài 3: Kiểm tra thông tin Tensor

In [7]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Bài 4: Slicing và Indexing

In [8]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-1.9820, -0.7577, -2.0920, -0.5773, -0.0153],
         [ 0.5135, -0.3494, -0.0939,  1.0318,  0.2566],
         [-0.1708,  1.6107,  1.4016, -1.1441,  0.8052],
         [-1.2492, -0.0718,  1.6453,  0.0833, -0.1057]],

        [[ 0.4126,  0.0653,  1.3270,  0.3095, -2.0264],
         [-0.0065, -1.5976, -0.9165,  1.2874,  0.8811],
         [ 3.0447, -1.3542, -0.2505,  1.4441, -0.2334],
         [ 2.0170,  0.3365, -0.8568, -2.0514,  0.0105]],

        [[-2.1496, -0.8436, -1.1091,  0.8898,  0.9510],
         [-1.8595,  1.4417,  1.7458, -0.7555,  1.3131],
         [ 1.1925,  2.4434, -0.1165, -0.7168, -0.6227],
         [ 1.0825,  0.7668, -1.0098,  0.7720, -2.1646]]])

Tensor a[1]:
tensor([[ 0.4126,  0.0653,  1.3270,  0.3095, -2.0264],
        [-0.0065, -1.5976, -0.9165,  1.2874,  0.8811],
        [ 3.0447, -1.3542, -0.2505,  1.4441, -0.2334],
        [ 2.0170,  0.3365, -0.8568, -2.0514,  0.0105]])

Tensor a[1:, 2:4]:
tensor([[[ 3.0447, -1.3542, -0.2505,  1.4441, -0.2

Bài 5: Reshape và Flatten

In [9]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[ 0.5537, -0.9763,  1.3324, -1.6581],
        [-1.9964, -0.6686, -0.0909, -0.4981],
        [-1.6491, -0.7264,  0.8806, -0.3610]])

Flatten:
tensor([ 0.5537, -0.9763,  1.3324, -1.6581, -1.9964, -0.6686, -0.0909, -0.4981,
        -1.6491, -0.7264,  0.8806, -0.3610])

Reshape to 3 x 2 x 2:
tensor([[[ 0.5537, -0.9763],
         [ 1.3324, -1.6581]],

        [[-1.9964, -0.6686],
         [-0.0909, -0.4981]],

        [[-1.6491, -0.7264],
         [ 0.8806, -0.3610]]])


Bài 6: Phép toán và nhân ma trận

In [10]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 2.5220,  0.3199, -0.2498],
        [ 1.0472, -1.3862, -0.3691]])
b:
tensor([[ 0.4083, -1.1355, -0.6062],
        [-0.7808,  1.5328,  0.3055]])

a + b:
tensor([[ 2.9303, -0.8155, -0.8560],
        [ 0.2664,  0.1466, -0.0636]])

a / b:
tensor([[ 6.1771, -0.2818,  0.4121],
        [-1.3412, -0.9044, -1.2081]])

a^2:
tensor([[6.3605, 0.1024, 0.0624],
        [1.0966, 1.9215, 0.1362]])

Matrix multiplication:
tensor([[ 0.8178, -1.5551],
        [ 2.2252, -3.0551]])


Bài 7: Các hàm thống kê trên Tensor

In [18]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[-1.3771,  0.0553, -1.7313,  0.0455],
        [-0.2708,  0.1078,  1.1424, -1.2332],
        [ 0.8133, -0.1364,  0.9459, -0.0271]])

Mean:
tensor([-0.2782,  0.0089,  0.1190, -0.4049])

Standard deviation:
tensor([1.0952, 0.1285, 1.6054, 0.7182])

Cumulative sum:
tensor([[-1.3771,  0.0553, -1.7313,  0.0455],
        [-1.6479,  0.1631, -0.5889, -1.1877],
        [-0.8346,  0.0267,  0.3570, -1.2148]])


Bài 8: Autograd cơ bản

In [17]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


Bài 9: Gradient Descent tìm hệ số đa thức

In [ ]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
optimizer.zero_grad()
y_pred = x @ w
mse = torch.mean(torch.square(y - y_pred))
mse.backward()
optimizer.step()
print("Learned coefficients:")
print(w)

IndentationError: expected an indented block after 'for' statement on line 18 (528036015.py, line 19)

Bài 10: Giải hệ phương trình bằng Autograd

In [ ]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
y1 = A + B - 9
y2 = C - D - 1
y3 = A + C - 8
y4 = B - D - 2
sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
optimizer.zero_grad()
sqerr.backward()
optimizer.step()
print("A =", A)
print("B =", B)
print("C =", C)
print("D =", D)

IndentationError: expected an indented block after 'for' statement on line 9 (525960359.py, line 10)