In [14]:
import pandas
import matplotlib
import torch
import numpy

Bài 1: Tạo 1 Tensor

In [5]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


Bài 2: Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.4935, 0.5258, 0.6848, 0.9740],
        [0.4850, 0.7258, 0.7654, 0.7310],
        [0.9644, 0.4962, 0.3859, 0.0829]])
tensor([[ 1.1725, -2.7046, -0.3612,  0.3750],
        [-0.2229, -0.4474,  0.4594, -1.5648],
        [-0.3225, -0.8927,  2.0204, -0.3733]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


In [3]:
f = torch.full((5, 5), 10)
print(f)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


Bài 3: Kiểm tra thông tin Tensor

In [7]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Bài 4: Slicing và Indexing

In [5]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.5220,  0.5011,  1.9023,  0.4980, -1.1128],
         [-0.9331,  1.9583,  1.1168,  0.4105, -1.1978],
         [-2.7045, -0.5708, -1.5656, -0.2523, -0.5266],
         [ 1.1596,  0.6723,  1.7175,  1.6030,  0.2552]],

        [[-1.8983,  0.6351, -1.2192,  0.1289,  1.5508],
         [ 0.0051, -0.9633, -1.2648,  0.4207,  0.2845],
         [-0.1370, -0.5833, -0.2297, -0.4816,  1.4792],
         [ 0.2724, -0.3295,  1.4146,  0.2155,  0.7806]],

        [[-0.3146, -0.7970,  0.5468, -0.4286,  0.6290],
         [-1.0133,  0.0766, -1.2071, -1.2179, -0.4373],
         [-1.9815, -1.6399,  0.4144,  0.4510, -0.3369],
         [ 1.0897, -0.8608, -0.5645, -1.4586, -0.7149]]])

Tensor a[1]:
tensor([[-1.8983,  0.6351, -1.2192,  0.1289,  1.5508],
        [ 0.0051, -0.9633, -1.2648,  0.4207,  0.2845],
        [-0.1370, -0.5833, -0.2297, -0.4816,  1.4792],
        [ 0.2724, -0.3295,  1.4146,  0.2155,  0.7806]])

Tensor a[1:, 2:4]:
tensor([[[-0.1370, -0.5833, -0.2297, -0.4816,  1.4

In [6]:
print("Hai phần tử cuối trên chiều thứ ba:")
print(a[:, :, -2:])

Hai phần tử cuối trên chiều thứ ba:
tensor([[[ 0.4980, -1.1128],
         [ 0.4105, -1.1978],
         [-0.2523, -0.5266],
         [ 1.6030,  0.2552]],

        [[ 0.1289,  1.5508],
         [ 0.4207,  0.2845],
         [-0.4816,  1.4792],
         [ 0.2155,  0.7806]],

        [[-0.4286,  0.6290],
         [-1.2179, -0.4373],
         [ 0.4510, -0.3369],
         [-1.4586, -0.7149]]])


Bài 5: Reshape và Flatten

In [8]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.5171,  0.8850,  0.3432,  0.0284],
        [-0.2733, -0.2709,  0.4294, -0.1432],
        [ 0.0508,  1.3996, -1.0602, -0.1810]])

Flatten:
tensor([-0.5171,  0.8850,  0.3432,  0.0284, -0.2733, -0.2709,  0.4294, -0.1432,
         0.0508,  1.3996, -1.0602, -0.1810])

Reshape to 3 x 2 x 2:
tensor([[[-0.5171,  0.8850],
         [ 0.3432,  0.0284]],

        [[-0.2733, -0.2709],
         [ 0.4294, -0.1432]],

        [[ 0.0508,  1.3996],
         [-1.0602, -0.1810]]])


In [9]:
print("\nReshape to 2 x 6:")
print(a.reshape(2, 6))


Reshape to 2 x 6:
tensor([[-0.5171,  0.8850,  0.3432,  0.0284, -0.2733, -0.2709],
        [ 0.4294, -0.1432,  0.0508,  1.3996, -1.0602, -0.1810]])


Bài 6: Phép toán và nhân ma trận

In [10]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 2.5220,  0.3199, -0.2498],
        [ 1.0472, -1.3862, -0.3691]])
b:
tensor([[ 0.4083, -1.1355, -0.6062],
        [-0.7808,  1.5328,  0.3055]])

a + b:
tensor([[ 2.9303, -0.8155, -0.8560],
        [ 0.2664,  0.1466, -0.0636]])

a / b:
tensor([[ 6.1771, -0.2818,  0.4121],
        [-1.3412, -0.9044, -1.2081]])

a^2:
tensor([[6.3605, 0.1024, 0.0624],
        [1.0966, 1.9215, 0.1362]])

Matrix multiplication:
tensor([[ 0.8178, -1.5551],
        [ 2.2252, -3.0551]])


Bài 7: Các hàm thống kê trên Tensor

In [10]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 0.5522, -0.1248,  2.2498, -0.3017],
        [ 0.7357, -0.1139, -0.9586, -0.9863],
        [ 1.8104, -2.6884, -0.9937, -0.5781]])

Mean:
tensor([ 1.0328, -0.9757,  0.0992, -0.6220])

Standard deviation:
tensor([0.6797, 1.4833, 1.8626, 0.3444])

Cumulative sum:
tensor([[ 0.5522, -0.1248,  2.2498, -0.3017],
        [ 1.2879, -0.2387,  1.2913, -1.2880],
        [ 3.0984, -2.9271,  0.2976, -1.8660]])


In [11]:
print("Mean (dim=1):")
print(torch.mean(a, dim=1))
print("\nStandard deviation (dim=1):")
print(torch.std(a, dim=1))
print("\nCumulative sum (dim=1):")
print(torch.cumsum(a, dim=1))

Mean (dim=1):
tensor([ 0.5939, -0.3308, -0.6124])

Standard deviation (dim=1):
tensor([1.1637, 0.8182, 1.8553])

Cumulative sum (dim=1):
tensor([[ 0.5522,  0.4274,  2.6772,  2.3756],
        [ 0.7357,  0.6218, -0.3368, -1.3231],
        [ 1.8104, -0.8780, -1.8716, -2.4497]])


Bài 8: Autograd cơ bản

In [17]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


In [12]:
import torch

x = torch.tensor(3.6, requires_grad=True)
y = 3 * x**2 + 2 * x + 1
y.backward()

print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(47.0800, grad_fn=<AddBackward0>)
x.grad = tensor(23.6000)


Bài 9: Gradient Descent tìm hệ số đa thức

In [14]:
import numpy as np
import torch

torch.manual_seed(0)
np.random.seed(0)

polynomial = np.poly1d([1, 2, 3])   # x^2 + 2x + 3
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X).astype(np.float32)

XX = np.hstack([
    X * X,
    X,
    np.ones_like(X)
])

w = torch.randn(3, 1, requires_grad=True, dtype=torch.float32)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

print("Initial coefficients:")
print(w)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[ 1.5410],
        [-0.2934],
        [-2.1788]], requires_grad=True)
Learned coefficients:
tensor([[1.0017],
        [2.0058],
        [2.8337]], requires_grad=True)


Bài 10: Giải hệ phương trình bằng Autograd

In [16]:
import random
import torch

torch.manual_seed(0)
random.seed(0)

A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2

    sqerr = y1 * y1 + y2 * y2 + y3 * y3 + y4 * y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

print("A =", A.item())
print("B =", B.item())
print("C =", C.item())
print("D =", D.item())

A = 4.549361705780029
B = 4.450590133666992
C = 3.4506072998046875
D = 2.450596809387207


In [17]:
print("A + B =", A + B)   # kỳ vọng ≈ 9
print("C - D =", C - D)   # kỳ vọng ≈ 1
print("A + C =", A + C)   # kỳ vọng ≈ 8
print("B - D =", B - D)   # kỳ vọng ≈ 2

A + B = tensor(9.0000, grad_fn=<AddBackward0>)
C - D = tensor(1.0000, grad_fn=<SubBackward0>)
A + C = tensor(8.0000, grad_fn=<AddBackward0>)
B - D = tensor(2.0000, grad_fn=<SubBackward0>)
